# Generated by Django 4.2.6 on 2023-11-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the pet')),
                ('age', models.IntegerField(default=0, verbose_name='Age in years')),
                ('description', models.TextField(blank=True, null=True, verbose_name='General description')),
                ('adopted', models.BooleanField(verbose_name='Is adopted?')),
                ('create_at', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pet.specie', verbose_name="Pet's specie")),
            ],
        ),
    ]
