# Generated by Django 4.2.6 on 2023-11-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet.race', verbose_name="Pet's race"),
        ),
    ]
