# Generated by Django 4.2.6 on 2024-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(null=True, verbose_name='Is adopted?'),
        ),
    ]
