# Generated by Django 4.2.6 on 2024-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_pet_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
