# Generated by Django 4.2.6 on 2024-11-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pet.race', verbose_name="Pet's race"),
        ),
    ]
