# Generated by Django 4.2.6 on 2024-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_pet_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is adopted?'),
        ),
    ]
