# Generated by Django 4.2.6 on 2024-11-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_pet_adopted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ('name',)},
        ),
    ]
