# Generated by Django 4.2.6 on 2024-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_alter_pet_options_alter_race_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=True, verbose_name='Is adopted?'),
        ),
    ]
