# Generated by Django 4.2.6 on 2024-11-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_pet_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False, verbose_name='Is adopted?'),
        ),
    ]
